### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by travigd** [JuliaGizmos/WebIO.jl#368]
This issue is meant to keep track of what needs to do/has been done to release WebIO v1.0.

- [ ] Update to JSExpr v1 (#356)
- [ ] Synchronous observable updates (#367)
- [ ] Add renderable trait (#361, this might deserve more discussion)
- [ ] Improve serialization for IJulia (#351)
- [ ] Finalize extensible messaging protocol (#323)
- [ ] Implement scope reaping (#321)
- [ ] Implement Observable pull-on-mount behavior (#258)
- [ ] Remove deprecations

I think there will be some fairly large API changes. I'm not too worried about it because most users of WebIO are really just using Interact/PlotlyJS/MeshCat and we can make sure that WebIO works for those uses cases.
